version: '3.8'
services:

  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_URL: postgres://admin:pwd@localhost:5432/smart-brain
      POSTGRES_DB_NAME: smart-brain
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  smart-brain-api:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables" 
    container_name: backend
    # image: node:16.12.0
    build: ./
    volumes:
      - ./:/usr/src/smart-brain-api
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:PWD@postgres:5432/smart-brain
      REDIS_URI: redis://redis:6379
    # Heads up! Docker has updated this feature and now you don't need to define the links property in order for things to work - https://docs.docker.com/compose/networking/
    # links:
    #   - postgres
    #   - redis
